using Chronos.ORM;
using Chronos.ORM.SubSonic.SQLGeneration.Schema;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Chronos.Server.Databases.Characters
{
    [TableName("characters")]
    public class CharacterRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string Name { get; set; }
        public int SceneId { get; set; }
        public bool Sex { get; set; }
        public Single X { get; set; }
        public Single Y { get; set; }
        public Single Z { get; set; }
        public int Level { get; set; }
        public int Job { get; set; }
        public int Strenght { get; set; }
        public int Stamina { get; set; }
        public int Dexterity { get; set; }
        public int Intelligence { get; set; }
        public int SPI { get; set; }
        public int HairMesh { get; set; }
        public int HairColor { get; set; }
        public int HeadMesh { get; set; }
        public DateTime BlockTime { get; set; }
    }
}
