using Chronos.ORM;
using Chronos.ORM.SubSonic.SQLGeneration.Schema;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Chronos.Server.Databases.Breeds
{
    [TableName("breeds")]
    public class BreedRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Job")]
        public byte Job { get; set; }
        public int StartMap { get; set; }
        public Single StartX { get; set; }
        public Single StartY { get; set; }
        public Single StartZ { get; set; }
        public int StartLevel { get; set; }
        public int StartStrenght { get; set; }
        public int StartStamina { get; set; }
        public int StartDexterity { get; set; }
        public int StartIntelligence { get; set; }
        public int StartSPI { get; set; }
        public int StartHP { get; set; }
        public int StartMP { get; set; }
        public int StartMoney { get; set; }
    }
    public class BreedRecordRelator
    {
        public const string FetchQuery = "SELECT * FROM breeds";
    }
}