using Chronos.ORM;
using Chronos.ORM.SubSonic.SQLGeneration.Schema;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Chronos.Server.Databases.Items
{
    [TableName("characters_items")]
    public class ItemRecord : IAutoGeneratedRecord
    {
        [PrimaryKey("Id")]
        public int Id { get; set; }
        public int OwnerId { get; set; }
        public byte Slot { get; set; }
        public uint ItemId { get; set; }
        public uint Word { get; set; }
        public int Option { get; set; }
        public uint Quantity { get; set; }
    }
    public class ItemRecordRelator
    {
        public const string FetchQueryByOwnerId = "SELECT * FROM characters_items WHERE OwnerId={0}";
    }
}
